### PR TITLE
Make use of faster preset and multithreaded minimap2

### PR DESCRIPTION
**Pull request by Ge0rges**
Switched to using the new version of minimap2 which has the new `LrHq` preset and multithreading.

Make use of that 4x faster preset.
Implement multithreading (I think it works?) for #18

### CODE REVIEW

**Comment by wdecoster** [comment]
Thank you @Ge0rges! Looks mostly okay, but the automated test reported two errors. Could you take a look at it? If necessary, I can  help :)

**Comment by Ge0rges** [comment]
Checking it out right now

**Comment by Ge0rges** [comment]
@wdecoster should work now, I forgot to update the test functions.

**Comment by wdecoster** [comment]
Looks good! At some point, we should probably deal with the warning here:
https://github.com/wdecoster/chopper/actions/runs/8317985884/job/22759454860?pr=26#step:4:128

**Comment by Ge0rges** [comment]
Yeah I wasn't sure what that was about so I decided to leave it be for now.

**Comment by Ge0rges** [comment]
It might be worth mentioning somewhere that we use LrHq in case someone is still using older chemistry.

**Comment by Ge0rges** [comment]
Oh I also did not bump the version number for a new release as I thought that was your purview.

**Comment by Ge0rges** [comment]
@wdecoster do you think the PR merits a version bump and package?

**Comment by wdecoster** [comment]
Yes, I need to make a new release. Hmm,  the older chemistry won't immediately go away. I am not yet sure what the best solution is.

**Pull request merged**
